version: "3.8"

services:
  hadoop-master:
    image: kancve/hadoop-mr4c
    hostname: hadoop-master
    volumes:
      - ./volumes/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./volumes/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./volumes/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./volumes/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./volumes/entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /opt/entrypoint.sh master
    deploy:
      endpoint_mode: dnsrr

  hadoop-worker1:
    image: kancve/hadoop-mr4c
    hostname: hadoop-worker1
    volumes:
      - ./volumes/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./volumes/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./volumes/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./volumes/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./volumes/entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /opt/entrypoint.sh worker
    deploy:
      endpoint_mode: dnsrr

  hadoop-worker2:
    image: kancve/hadoop-mr4c
    hostname: hadoop-worker2
    volumes:
      - ./volumes/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./volumes/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./volumes/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./volumes/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./volumes/entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /opt/entrypoint.sh worker
    deploy:
      endpoint_mode: dnsrr

  hadoop-worker3:
    image: kancve/hadoop-mr4c
    hostname: hadoop-worker3
    volumes:
      - ./volumes/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./volumes/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./volumes/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./volumes/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./volumes/entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /opt/entrypoint.sh worker
    deploy:
      endpoint_mode: dnsrr

  portainer:
    image: portainer/portainer:1.24.1
    hostname: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./volumes/portainer:/data
    deploy:
      mode: replicated
      replicas: 1

  nginx:
    image: nginx:1.19.6
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - hadoop-master
      - portainer
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  default:
    driver: overlay
    attachable: true
